import uuid
from abc import ABC, abstractmethod

from app.domain.entities.award import Award


class AwardRepository(ABC):
    @abstractmethod
    async def create(self, award: Award) -> Award: ...
    @abstractmethod
    async def get_by_id(self, award_id: uuid.UUID) -> Award | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[Award]: ...
    @abstractmethod
    async def update(self, award: Award) -> Award: ...
    @abstractmethod
    async def delete(self, award_id: uuid.UUID) -> None: ...
    @abstractmethod
    async def bulk_create(self, awards: list[Award]) -> list[Award]: ...
    @abstractmethod
    async def delete_all_for_user(self, user_id: uuid.UUID) -> None: ...
