import uuid
from abc import ABC, abstractmethod

from app.domain.entities.blog import Blog


class BlogRepository(ABC):
    @abstractmethod
    async def create(self, blog: Blog) -> Blog: ...
    @abstractmethod
    async def get_by_id(self, blog_id: uuid.UUID) -> Blog | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[Blog]: ...
    @abstractmethod
    async def update(self, blog: Blog) -> Blog: ...
    @abstractmethod
    async def delete(self, blog_id: uuid.UUID) -> None: ...
    @abstractmethod
    async def bulk_create(self, blogs: list[Blog]) -> list[Blog]: ...
    @abstractmethod
    async def delete_all_for_user(self, user_id: uuid.UUID) -> None: ...
