import uuid
from abc import ABC, abstractmethod

from app.domain.entities.certification import Certification


class CertificationRepository(ABC):
    @abstractmethod
    async def create(self, cert: Certification) -> Certification: ...
    @abstractmethod
    async def get_by_id(self, cert_id: uuid.UUID) -> Certification | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[Certification]: ...
    @abstractmethod
    async def update(self, cert: Certification) -> Certification: ...
    @abstractmethod
    async def delete(self, cert_id: uuid.UUID) -> None: ...
    @abstractmethod
    async def bulk_create(self, certs: list[Certification]) -> list[Certification]: ...
    @abstractmethod
    async def delete_all_for_user(self, user_id: uuid.UUID) -> None: ...
