import uuid
from abc import ABC, abstractmethod

from app.domain.entities.education import Education


class EducationRepository(ABC):
    @abstractmethod
    async def create(self, education: Education) -> Education: ...
    @abstractmethod
    async def get_by_id(self, education_id: uuid.UUID) -> Education | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[Education]: ...
    @abstractmethod
    async def update(self, education: Education) -> Education: ...
    @abstractmethod
    async def delete(self, education_id: uuid.UUID) -> None: ...
    @abstractmethod
    async def bulk_create(self, entries: list[Education]) -> list[Education]: ...
    @abstractmethod
    async def delete_all_for_user(self, user_id: uuid.UUID) -> None: ...
