import uuid
from abc import ABC, abstractmethod

from app.domain.entities.language import Language


class LanguageRepository(ABC):
    @abstractmethod
    async def create(self, language: Language) -> Language: ...
    @abstractmethod
    async def get_by_id(self, lang_id: uuid.UUID) -> Language | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[Language]: ...
    @abstractmethod
    async def update(self, language: Language) -> Language: ...
    @abstractmethod
    async def delete(self, lang_id: uuid.UUID) -> None: ...
    @abstractmethod
    async def bulk_create(self, languages: list[Language]) -> list[Language]: ...
    @abstractmethod
    async def delete_all_for_user(self, user_id: uuid.UUID) -> None: ...
