import uuid
from abc import ABC, abstractmethod

from app.domain.entities.publication import Publication


class PublicationRepository(ABC):
    @abstractmethod
    async def create(self, pub: Publication) -> Publication: ...
    @abstractmethod
    async def get_by_id(self, pub_id: uuid.UUID) -> Publication | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[Publication]: ...
    @abstractmethod
    async def update(self, pub: Publication) -> Publication: ...
    @abstractmethod
    async def delete(self, pub_id: uuid.UUID) -> None: ...
    @abstractmethod
    async def bulk_create(self, pubs: list[Publication]) -> list[Publication]: ...
    @abstractmethod
    async def delete_all_for_user(self, user_id: uuid.UUID) -> None: ...
