import uuid
from abc import ABC, abstractmethod

from app.domain.entities.skill import Skill


class SkillRepository(ABC):
    @abstractmethod
    async def create(self, skill: Skill) -> Skill: ...
    @abstractmethod
    async def get_by_id(self, skill_id: uuid.UUID) -> Skill | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[Skill]: ...
    @abstractmethod
    async def update(self, skill: Skill) -> Skill: ...
    @abstractmethod
    async def delete(self, skill_id: uuid.UUID) -> None: ...
    @abstractmethod
    async def bulk_create(self, skills: list[Skill]) -> list[Skill]: ...
    @abstractmethod
    async def delete_all_for_user(self, user_id: uuid.UUID) -> None: ...
