import uuid
from abc import ABC, abstractmethod

from app.domain.entities.technology import Technology


class TechnologyRepository(ABC):
    @abstractmethod
    async def create(self, tech: Technology) -> Technology: ...
    @abstractmethod
    async def get_by_id(self, tech_id: uuid.UUID) -> Technology | None: ...
    @abstractmethod
    async def get_by_user_id(self, user_id: uuid.UUID) -> list[Technology]: ...
    @abstractmethod
    async def update(self, tech: Technology) -> Technology: ...
    @abstractmethod
    async def delete(self, tech_id: uuid.UUID) -> None: ...
    @abstractmethod
    async def bulk_create(self, techs: list[Technology]) -> list[Technology]: ...
    @abstractmethod
    async def delete_all_for_user(self, user_id: uuid.UUID) -> None: ...
