/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DashboardResumesIndexRouteImport } from './routes/dashboard/resumes/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/dashboard/profile/index'
import { Route as DashboardOptimizeIndexRouteImport } from './routes/dashboard/optimize/index'
import { Route as DashboardJobsIndexRouteImport } from './routes/dashboard/jobs/index'
import { Route as DashboardAtsIndexRouteImport } from './routes/dashboard/ats/index'
import { Route as DashboardResumesIdRouteImport } from './routes/dashboard/resumes/$id'
import { Route as DashboardJobsIdRouteImport } from './routes/dashboard/jobs/$id'
import { Route as DashboardAtsIdRouteImport } from './routes/dashboard/ats/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardResumesIndexRoute = DashboardResumesIndexRouteImport.update({
  id: '/resumes/',
  path: '/resumes/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOptimizeIndexRoute = DashboardOptimizeIndexRouteImport.update({
  id: '/optimize/',
  path: '/optimize/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsIndexRoute = DashboardJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAtsIndexRoute = DashboardAtsIndexRouteImport.update({
  id: '/ats/',
  path: '/ats/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardResumesIdRoute = DashboardResumesIdRouteImport.update({
  id: '/resumes/$id',
  path: '/resumes/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsIdRoute = DashboardJobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAtsIdRoute = DashboardAtsIdRouteImport.update({
  id: '/ats/$id',
  path: '/ats/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ats/$id': typeof DashboardAtsIdRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/resumes/$id': typeof DashboardResumesIdRoute
  '/dashboard/ats/': typeof DashboardAtsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/optimize/': typeof DashboardOptimizeIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/resumes/': typeof DashboardResumesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ats/$id': typeof DashboardAtsIdRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/resumes/$id': typeof DashboardResumesIdRoute
  '/dashboard/ats': typeof DashboardAtsIndexRoute
  '/dashboard/jobs': typeof DashboardJobsIndexRoute
  '/dashboard/optimize': typeof DashboardOptimizeIndexRoute
  '/dashboard/profile': typeof DashboardProfileIndexRoute
  '/dashboard/resumes': typeof DashboardResumesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ats/$id': typeof DashboardAtsIdRoute
  '/dashboard/jobs/$id': typeof DashboardJobsIdRoute
  '/dashboard/resumes/$id': typeof DashboardResumesIdRoute
  '/dashboard/ats/': typeof DashboardAtsIndexRoute
  '/dashboard/jobs/': typeof DashboardJobsIndexRoute
  '/dashboard/optimize/': typeof DashboardOptimizeIndexRoute
  '/dashboard/profile/': typeof DashboardProfileIndexRoute
  '/dashboard/resumes/': typeof DashboardResumesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/'
    | '/dashboard/ats/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/resumes/$id'
    | '/dashboard/ats/'
    | '/dashboard/jobs/'
    | '/dashboard/optimize/'
    | '/dashboard/profile/'
    | '/dashboard/resumes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/dashboard'
    | '/dashboard/ats/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/resumes/$id'
    | '/dashboard/ats'
    | '/dashboard/jobs'
    | '/dashboard/optimize'
    | '/dashboard/profile'
    | '/dashboard/resumes'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/login'
    | '/dashboard/'
    | '/dashboard/ats/$id'
    | '/dashboard/jobs/$id'
    | '/dashboard/resumes/$id'
    | '/dashboard/ats/'
    | '/dashboard/jobs/'
    | '/dashboard/optimize/'
    | '/dashboard/profile/'
    | '/dashboard/resumes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/resumes/': {
      id: '/dashboard/resumes/'
      path: '/resumes'
      fullPath: '/dashboard/resumes/'
      preLoaderRoute: typeof DashboardResumesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile/': {
      id: '/dashboard/profile/'
      path: '/profile'
      fullPath: '/dashboard/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/optimize/': {
      id: '/dashboard/optimize/'
      path: '/optimize'
      fullPath: '/dashboard/optimize/'
      preLoaderRoute: typeof DashboardOptimizeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs/': {
      id: '/dashboard/jobs/'
      path: '/jobs'
      fullPath: '/dashboard/jobs/'
      preLoaderRoute: typeof DashboardJobsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ats/': {
      id: '/dashboard/ats/'
      path: '/ats'
      fullPath: '/dashboard/ats/'
      preLoaderRoute: typeof DashboardAtsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/resumes/$id': {
      id: '/dashboard/resumes/$id'
      path: '/resumes/$id'
      fullPath: '/dashboard/resumes/$id'
      preLoaderRoute: typeof DashboardResumesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/jobs/$id': {
      id: '/dashboard/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/dashboard/jobs/$id'
      preLoaderRoute: typeof DashboardJobsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ats/$id': {
      id: '/dashboard/ats/$id'
      path: '/ats/$id'
      fullPath: '/dashboard/ats/$id'
      preLoaderRoute: typeof DashboardAtsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAtsIdRoute: typeof DashboardAtsIdRoute
  DashboardJobsIdRoute: typeof DashboardJobsIdRoute
  DashboardResumesIdRoute: typeof DashboardResumesIdRoute
  DashboardAtsIndexRoute: typeof DashboardAtsIndexRoute
  DashboardJobsIndexRoute: typeof DashboardJobsIndexRoute
  DashboardOptimizeIndexRoute: typeof DashboardOptimizeIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardResumesIndexRoute: typeof DashboardResumesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAtsIdRoute: DashboardAtsIdRoute,
  DashboardJobsIdRoute: DashboardJobsIdRoute,
  DashboardResumesIdRoute: DashboardResumesIdRoute,
  DashboardAtsIndexRoute: DashboardAtsIndexRoute,
  DashboardJobsIndexRoute: DashboardJobsIndexRoute,
  DashboardOptimizeIndexRoute: DashboardOptimizeIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardResumesIndexRoute: DashboardResumesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
